### PR TITLE
Fix compilation issues due to toxcore API changes

### LINKED ISSUE #4: Change to group messaging API in latest toxcore
# github.com/organ/golibtox
.gvm/pkgsets/go1.3/global/src/github.com/organ/golibtox/golibtox.go:797: not enough arguments in call to _Cfunc_tox_join_groupchat
.gvm/pkgsets/go1.3/global/src/github.com/organ/golibtox/golibtox.go:816: cannot use C.uint32_t(len(message)) (type C.uint32_t) as type C.uint16_t in argument to _Cfunc_tox_group_message_send
.gvm/pkgsets/go1.3/global/src/github.com/organ/golibtox/golibtox.go:835: cannot use C.uint32_t(len(action)) (type C.uint32_t) as type C.uint16_t in argument to _Cfunc_tox_group_action_send

### PR DESCRIPTION
**Pull request by nikwen**
Fixes https://github.com/organ/golibtox/issues/4 as well as other compilation issues.

Thanks for creating this library by the way. :)

### CODE REVIEW

**Comment by haltingstate** [comment]
Thanks for fixing that! New error

# github.com/nikwen/golibtox
../../.gvm/pkgsets/go1.3/global/src/github.com/nikwen/golibtox/golibtox.go:181: unknown C.struct___0 field 'proxy_enabled' in struct literal

**Comment by nikwen** [comment]
The tox API is constantly evolving. To keep up with newer versions, you'll regularly have to fix errors like this one.

**Comment by F0rth** [comment]
I've juste fixed this one.

**Comment by nikwen** [comment]
Thanks for merging. :)

**Pull request merged**
